# Numpy introduction

In [ ]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
X.ndim

2

In [ ]:
X.shape

(2, 3)

#### Generowanie tablic

In [ ]:
X = np.zeros(shape=(3,6))
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
X = np.ones((4,5), dtype='int')
X

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
X = np.full(shape=(3,4), fill_value = 21.37)
X

array([[21.37, 21.37, 21.37, 21.37],
       [21.37, 21.37, 21.37, 21.37],
       [21.37, 21.37, 21.37, 21.37]])

In [ ]:
X = np.arange(3, 9, 0.3)
X

array([3. , 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6,
       6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7])

In [ ]:
X.shape

(20,)

In [ ]:
X = X.reshape(4, -1)
X

array([[3. , 3.3, 3.6, 3.9, 4.2],
       [4.5, 4.8, 5.1, 5.4, 5.7],
       [6. , 6.3, 6.6, 6.9, 7.2],
       [7.5, 7.8, 8.1, 8.4, 8.7]])

In [ ]:
X.reshape(5,-1)

array([[3. , 3.3, 3.6, 3.9],
       [4.2, 4.5, 4.8, 5.1],
       [5.4, 5.7, 6. , 6.3],
       [6.6, 6.9, 7.2, 7.5],
       [7.8, 8.1, 8.4, 8.7]])

In [ ]:
X.reshape(2,2,-1)

array([[[3. , 3.3, 3.6, 3.9, 4.2],
        [4.5, 4.8, 5.1, 5.4, 5.7]],

       [[6. , 6.3, 6.6, 6.9, 7.2],
        [7.5, 7.8, 8.1, 8.4, 8.7]]])

In [ ]:
X = np.linspace(start=0, stop=3, num=16)
X

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. ])

#### Działania na macierzach

In [ ]:
A = np.array([[1, 2], [3,4]])
print(A)
B = np.array([[1, 1], [1,1]])
print(B)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [ ]:
print(A + B)
print(np.add(A, B))

[[2 3]
 [4 5]]
[[2 3]
 [4 5]]


In [ ]:
print(A - B)
print(np.subtract(A, B))

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [ ]:
print(A * B)
print(np.multiply(A, B))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
print(A/B)
print(np.divide(B, A))

[[1. 2.]
 [3. 4.]]
[[1.         0.5       ]
 [0.33333333 0.25      ]]


In [ ]:
A+3

array([[4, 5],
       [6, 7]])

In [ ]:
A/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
np.multiply(A, 3)

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
# Mnożenie macierzowe
print(A.dot(B))
print(np.dot(A, B))
print(A @ B)

[[3 3]
 [7 7]]
[[3 3]
 [7 7]]
[[3 3]
 [7 7]]


In [ ]:
print(B @ A)

[[4 6]
 [4 6]]


#### Liczby pseudolosowe

In [ ]:
np.random.seed(1)

In [ ]:
# Z rozkładu normalneg
print(np.random.randn())
print('')
print(np.random.randn(10))
print('')
print(np.random.randn(3,3))

1.6243453636632417

[-0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387   1.74481176
 -0.7612069   0.3190391  -0.24937038  1.46210794]

[[-2.06014071 -0.3224172  -0.38405435]
 [ 1.13376944 -1.09989127 -0.17242821]
 [-0.87785842  0.04221375  0.58281521]]


In [ ]:
# Liniowo z przedziału [0,1)
print(np.random.rand())
print('')
print(np.random.rand(10))
print('')
print(np.random.rand(3,3))

0.6918771139504734

[0.31551563 0.68650093 0.83462567 0.01828828 0.75014431 0.98886109
 0.74816565 0.28044399 0.78927933 0.10322601]

[[0.44789353 0.9085955  0.29361415]
 [0.28777534 0.13002857 0.01936696]
 [0.67883553 0.21162812 0.26554666]]


In [ ]:
# Całkowitoliczbowe
print(np.random.randint(10))
print('')
print(np.random.randint(low=10, high=20, size=6))

7

[17 19 17 13 10 18]


In [ ]:
X = np.arange(10, 0, -0.5)
X

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

In [ ]:
X = X.reshape(5, -1)
X

array([[10. ,  9.5,  9. ,  8.5],
       [ 8. ,  7.5,  7. ,  6.5],
       [ 6. ,  5.5,  5. ,  4.5],
       [ 4. ,  3.5,  3. ,  2.5],
       [ 2. ,  1.5,  1. ,  0.5]])

In [ ]:
np.random.shuffle(X)
X

array([[10. ,  9.5,  9. ,  8.5],
       [ 6. ,  5.5,  5. ,  4.5],
       [ 4. ,  3.5,  3. ,  2.5],
       [ 2. ,  1.5,  1. ,  0.5],
       [ 8. ,  7.5,  7. ,  6.5]])

In [ ]:
texts = np.array(["Ala", "ma", "kota", "sierotka", "Marysia"])
texts

array(['Ala', 'ma', 'kota', 'sierotka', 'Marysia'], dtype='<U8')

In [ ]:
np.random.choice(texts)

'Ala'

#### Iteracja

In [ ]:
print(X)

[[10.   9.5  9.   8.5]
 [ 6.   5.5  5.   4.5]
 [ 4.   3.5  3.   2.5]
 [ 2.   1.5  1.   0.5]
 [ 8.   7.5  7.   6.5]]


In [ ]:
for item in X.flat:
  print(item)

10.0
9.5
9.0
8.5
6.0
5.5
5.0
4.5
4.0
3.5
3.0
2.5
2.0
1.5
1.0
0.5
8.0
7.5
7.0
6.5


In [ ]:
print(X.ravel())

[10.   9.5  9.   8.5  6.   5.5  5.   4.5  4.   3.5  3.   2.5  2.   1.5
  1.   0.5  8.   7.5  7.   6.5]


In [ ]:
# Macierz transponowana
X.T

array([[10. ,  6. ,  4. ,  2. ,  8. ],
       [ 9.5,  5.5,  3.5,  1.5,  7.5],
       [ 9. ,  5. ,  3. ,  1. ,  7. ],
       [ 8.5,  4.5,  2.5,  0.5,  6.5]])

In [ ]:
np.transpose(X)

array([[10. ,  6. ,  4. ,  2. ,  8. ],
       [ 9.5,  5.5,  3.5,  1.5,  7.5],
       [ 9. ,  5. ,  3. ,  1. ,  7. ],
       [ 8.5,  4.5,  2.5,  0.5,  6.5]])

In [ ]:
# 2D slicing - najpierw wiersze, potem kolumny z tych wierszy - jak zwyczajny slicing
print(X[1:4, 1:3])


[[5.5 5. ]
 [3.5 3. ]
 [1.5 1. ]]


#### Maski logiczne

In [ ]:
X

array([[10. ,  9.5,  9. ,  8.5],
       [ 6. ,  5.5,  5. ,  4.5],
       [ 4. ,  3.5,  3. ,  2.5],
       [ 2. ,  1.5,  1. ,  0.5],
       [ 8. ,  7.5,  7. ,  6.5]])

In [ ]:
X < 3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
np.bitwise_and(X > 2, X%2 == 0)

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [ ]:
np.bitwise_or(X > 7, X%3 == 0, X <= 1)

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True,  True, False, False]])

#### Proste funkcje matematyczne

In [ ]:
# e^x
x = 1
np.exp(x)

2.718281828459045

In [ ]:
np.sqrt(16)

4.0

In [ ]:
# czy wszystkie != 0
np.all([1, 2, -1])

True

In [ ]:
# czy przynajmniej jedno != 0
np.any([1, 0, 0, -1])

True

In [ ]:
A = np.random.randint(0, 100, 6)
A

array([77,  6, 52, 85, 70,  2])

In [ ]:
# Maksimum
print(np.argmax(A))
print(A[np.argmax(A)])
print(np.max(A))

# Dla minimim analogicznie - argmin() i min()

3
85
85


In [ ]:
np.argsort(A)

array([5, 1, 2, 4, 0, 3])

In [ ]:
# średnia
np.mean(A)

48.666666666666664

In [ ]:
# mediana
np.median(A)

61.0

In [ ]:
# odchylenie standardowe
np.std(A)

33.134406421254766

In [ ]:
# Norma euklidesowa (długość wektora w R^n)
V = np.array([1, 2, 3, 4])
np.linalg.norm(V)

5.477225575051661

In [ ]:
# Odległość dwóch punktów w R^n
Y = np.array([0, 3, -2, 1])

np.linalg.norm(V - Y)

6.0

In [ ]:
# Mnożenie macierzy
X = np.array([[5, 3], [3, 9]])
Z = np.array([[1], [-1]])
np.dot(X, Z)

array([[ 2],
       [-6]])

In [ ]:
# Wyznacznik macierzy
X = np.arange(9)
np.random.shuffle(X)
X = X.reshape(3, -1)
X

array([[1, 2, 4],
       [6, 7, 0],
       [8, 3, 5]])

In [ ]:
np.linalg.det(X)

-176.99999999999994

In [ ]:
# Ślad macierzy - suma elementów na przekątnej
np.trace(X)

13

In [ ]:
# Macierz jednostkowa (ozn. I) - jedynki tylko na przekątnej, reszta zera
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Macierz odwrotna - B jest macierzą dowrotną A, gdy A@B == B@A == I (B ozn. A^(-1))
np.linalg.inv(X)

array([[-0.19774011, -0.01129944,  0.15819209],
       [ 0.16949153,  0.15254237, -0.13559322],
       [ 0.21468927, -0.07344633,  0.02824859]])

#### Statystyka

In [ ]:
test = np.linspace(start=4, stop=6, num=24)
np.random.shuffle(test)
test = test.reshape((4, -1))
test

array([[4.26086957, 4.17391304, 4.95652174, 4.43478261, 4.52173913,
        5.56521739],
       [5.30434783, 5.47826087, 5.65217391, 4.69565217, 4.7826087 ,
        5.2173913 ],
       [4.08695652, 5.04347826, 5.82608696, 4.86956522, 5.73913043,
        4.        ],
       [5.39130435, 6.        , 5.13043478, 5.91304348, 4.60869565,
        4.34782609]])

In [ ]:
print(test.sum())
print(np.sum(test))
print(test.sum(axis=0))
print(test.sum(axis=1))

120.0
120.0
[19.04347826 20.69565217 21.56521739 19.91304348 19.65217391 19.13043478]
[27.91304348 31.13043478 29.56521739 31.39130435]


In [ ]:
np.min(test, axis=0)

array([4.08695652, 4.17391304, 4.95652174, 4.43478261, 4.52173913,
       4.        ])

In [ ]:
np.max(test, axis=1)

array([5.56521739, 5.65217391, 5.82608696, 6.        ])

In [ ]:
# Średnia
print(np.mean(test, axis=0))

# Wariancja - średnia arytmetyczna kwadratów odchyleń od średniej arytmetycznej
print(np.var(test, axis=0))

# Odchylenie standardowe (sqrt(var))
print(np.std(test, axis=0))

print((np.std(test, axis=0))**2)

[4.76086957 5.17391304 5.39130435 4.97826087 4.91304348 4.7826087 ]
[0.34924386 0.44801512 0.12854442 0.31521739 0.2362949  0.40075614]
[0.59096857 0.66933932 0.35853092 0.56144224 0.48610173 0.63305303]
[0.34924386 0.44801512 0.12854442 0.31521739 0.2362949  0.40075614]
